<?php

namespace Database\Seeders;

use App\Models\LGA;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LGASeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $lgas = array(
            array('state_id' => '8','lga' => 'Abadam'),
            array('state_id' => '37','lga' => 'Abaji'),
            array('state_id' => '3','lga' => 'Abak'),
            array('state_id' => '12','lga' => 'Abakaliki'),
            array('state_id' => '1','lga' => 'Aba North'),
            array('state_id' => '1','lga' => 'Aba South'),
            array('state_id' => '26','lga' => 'Abeokuta North'),
            array('state_id' => '26','lga' => 'Abeokuta South'),
            array('state_id' => '9','lga' => 'Abi'),
            array('state_id' => '16','lga' => 'Aboh Mbaise'),
            array('state_id' => '32','lga' => 'Abua/Odual'),
            array('state_id' => '22','lga' => 'Adavi'),
            array('state_id' => '13','lga' => 'Ado Ekiti'),
            array('state_id' => '26','lga' => 'Ado-Odo/Ota'),
            array('state_id' => '29','lga' => 'Afijio'),
            array('state_id' => '12','lga' => 'Afikpo North'),
            array('state_id' => '12','lga' => 'Afikpo South?(Edda)'),
            array('state_id' => '25','lga' => 'Agaie'),
            array('state_id' => '7','lga' => 'Agatu'),
            array('state_id' => '25','lga' => 'Agwara'),
            array('state_id' => '24','lga' => 'Agege'),
            array('state_id' => '4','lga' => 'Aguata'),
            array('state_id' => '16','lga' => 'Ahiazu Mbaise'),
            array('state_id' => '32','lga' => 'Ahoada East'),
            array('state_id' => '32','lga' => 'Ahoada West'),
            array('state_id' => '22','lga' => 'Ajaokuta'),
            array('state_id' => '24','lga' => 'Ajeromi-Ifelodun'),
            array('state_id' => '19','lga' => 'Ajingi'),
            array('state_id' => '9','lga' => 'Akamkpa'),
            array('state_id' => '29','lga' => 'Akinyele'),
            array('state_id' => '15','lga' => 'Akko'),
            array('state_id' => '11','lga' => 'Akoko-Edo'),
            array('state_id' => '27','lga' => 'Akoko North-East'),
            array('state_id' => '27','lga' => 'Akoko North-West'),
            array('state_id' => '27','lga' => 'Akoko South-West'),
            array('state_id' => '27','lga' => 'Akoko South-East'),
            array('state_id' => '9','lga' => 'Akpabuyo'),
            array('state_id' => '32','lga' => 'Akuku-Toru'),
            array('state_id' => '27','lga' => 'Akure North'),
            array('state_id' => '27','lga' => 'Akure South'),
            array('state_id' => '30','lga' => 'Akwanga'),
            array('state_id' => '19','lga' => 'Albasu'),
            array('state_id' => '21','lga' => 'Aleiro'),
            array('state_id' => '24','lga' => 'Alimosho'),
            array('state_id' => '5','lga' => 'Alkaleri'),
            array('state_id' => '24','lga' => 'Amuwo-Odofin'),
            array('state_id' => '4','lga' => 'Anambra East'),
            array('state_id' => '4','lga' => 'Anambra West'),
            array('state_id' => '4','lga' => 'Anaocha'),
            array('state_id' => '32','lga' => 'Andoni'),
            array('state_id' => '14','lga' => 'Aninri'),
            array('state_id' => '10','lga' => 'Aniocha North'),
            array('state_id' => '36','lga' => 'Anka'),
            array('state_id' => '22','lga' => 'Ankpa'),
            array('state_id' => '7','lga' => 'Apa'),
            array('state_id' => '24','lga' => 'Apapa'),
            array('state_id' => '7','lga' => 'Ado'),
            array('state_id' => '34','lga' => 'Ardo Kola'),
            array('state_id' => '21','lga' => 'Arewa Dandi'),
            array('state_id' => '21','lga' => 'Argungu'),
            array('state_id' => '1','lga' => 'Arochukwu'),
            array('state_id' => '23','lga' => 'Asa'),
            array('state_id' => '32','lga' => 'Asari-Toru'),
            array('state_id' => '8','lga' => 'Askira/Uba'),
            array('state_id' => '28','lga' => 'Atakunmosa East'),
            array('state_id' => '28','lga' => 'Atakunmosa West'),
            array('state_id' => '29','lga' => 'Atiba'),
            array('state_id' => '29','lga' => 'Atisbo'),
            array('state_id' => '21','lga' => 'Augie'),
            array('state_id' => '17','lga' => 'Auyo'),
            array('state_id' => '30','lga' => 'Awe'),
            array('state_id' => '14','lga' => 'Awgu'),
            array('state_id' => '4','lga' => 'Awka North'),
            array('state_id' => '4','lga' => 'Awka South'),
            array('state_id' => '4','lga' => 'Ayamelum'),
            array('state_id' => '28','lga' => 'Aiyedaade'),
            array('state_id' => '28','lga' => 'Aiyedire'),
            array('state_id' => '17','lga' => 'Babura'),
            array('state_id' => '24','lga' => 'Badagry'),
            array('state_id' => '21','lga' => 'Bagudo'),
            array('state_id' => '19','lga' => 'Bagwai'),
            array('state_id' => '9','lga' => 'Bakassi'),
            array('state_id' => '31','lga' => 'Bokkos'),
            array('state_id' => '20','lga' => 'Bakori'),
            array('state_id' => '36','lga' => 'Bakura'),
            array('state_id' => '15','lga' => 'Balanga'),
            array('state_id' => '34','lga' => 'Bali'),
            array('state_id' => '8','lga' => 'Bama'),
            array('state_id' => '35','lga' => 'Bade'),
            array('state_id' => '31','lga' => 'Barkin Ladi'),
            array('state_id' => '23','lga' => 'Baruten'),
            array('state_id' => '22','lga' => 'Bassa'),
            array('state_id' => '31','lga' => 'Bassa'),
            array('state_id' => '20','lga' => 'Batagarawa'),
            array('state_id' => '20','lga' => 'Batsari'),
            array('state_id' => '5','lga' => 'Bauchi'),
            array('state_id' => '20','lga' => 'Baure'),
            array('state_id' => '8','lga' => 'Bayo'),
            array('state_id' => '19','lga' => 'Bebeji'),
            array('state_id' => '9','lga' => 'Bekwarra'),
            array('state_id' => '1','lga' => 'Bende'),
            array('state_id' => '9','lga' => 'Biase'),
            array('state_id' => '19','lga' => 'Bichi'),
            array('state_id' => '25','lga' => 'Bida'),
            array('state_id' => '15','lga' => 'Billiri'),
            array('state_id' => '20','lga' => 'Bindawa'),
            array('state_id' => '33','lga' => 'Binji'),
            array('state_id' => '17','lga' => 'Biriniwa'),
            array('state_id' => '18','lga' => 'Birnin Gwari'),
            array('state_id' => '21','lga' => 'Birnin Kebbi'),
            array('state_id' => '17','lga' => 'Birnin Kudu'),
            array('state_id' => '36','lga' => 'Birnin Magaji/Kiyaw'),
            array('state_id' => '8','lga' => 'Biu'),
            array('state_id' => '33','lga' => 'Bodinga'),
            array('state_id' => '5','lga' => 'Bogoro'),
            array('state_id' => '9','lga' => 'Boki'),
            array('state_id' => '28','lga' => 'Boluwaduro'),
            array('state_id' => '10','lga' => 'Bomadi'),
            array('state_id' => '32','lga' => 'Bonny'),
            array('state_id' => '25','lga' => 'Borgu'),
            array('state_id' => '28','lga' => 'Boripe'),
            array('state_id' => '35','lga' => 'Bursari'),
            array('state_id' => '25','lga' => 'Bosso'),
            array('state_id' => '6','lga' => 'Brass'),
            array('state_id' => '17','lga' => 'Buji'),
            array('state_id' => '36','lga' => 'Bukkuyum'),
            array('state_id' => '7','lga' => 'Buruku'),
            array('state_id' => '36','lga' => 'Bungudu'),
            array('state_id' => '19','lga' => 'Bunkure'),
            array('state_id' => '21','lga' => 'Bunza'),
            array('state_id' => '10','lga' => 'Burutu'),
            array('state_id' => '37','lga' => 'Bwari'),
            array('state_id' => '9','lga' => 'Calabar Municipal'),
            array('state_id' => '9','lga' => 'Calabar South'),
            array('state_id' => '25','lga' => 'Chanchaga'),
            array('state_id' => '20','lga' => 'Charanchi'),
            array('state_id' => '8','lga' => 'Chibok'),
            array('state_id' => '18','lga' => 'Chikun'),
            array('state_id' => '19','lga' => 'Dala'),
            array('state_id' => '35','lga' => 'Damaturu'),
            array('state_id' => '5','lga' => 'Damban'),
            array('state_id' => '19','lga' => 'Dambatta'),
            array('state_id' => '8','lga' => 'Damboa'),
            array('state_id' => '21','lga' => 'Dandi'),
            array('state_id' => '20','lga' => 'Dandume'),
            array('state_id' => '33','lga' => 'Dange Shuni'),
            array('state_id' => '20','lga' => 'Danja'),
            array('state_id' => '20','lga' => 'Dan Musa'),
            array('state_id' => '5','lga' => 'Darazo'),
            array('state_id' => '5','lga' => 'Dass'),
            array('state_id' => '20','lga' => 'Daura'),
            array('state_id' => '19','lga' => 'Dawakin Kudu'),
            array('state_id' => '19','lga' => 'Dawakin Tofa'),
            array('state_id' => '32','lga' => 'Degema'),
            array('state_id' => '22','lga' => 'Dekina'),
            array('state_id' => '2','lga' => 'Demsa'),
            array('state_id' => '8','lga' => 'Dikwa'),
            array('state_id' => '19','lga' => 'Doguwa'),
            array('state_id' => '30','lga' => 'Doma'),
            array('state_id' => '34','lga' => 'Donga'),
            array('state_id' => '15','lga' => 'Dukku'),
            array('state_id' => '4','lga' => 'Dunukofia'),
            array('state_id' => '17','lga' => 'Dutse'),
            array('state_id' => '20','lga' => 'Dutsi'),
            array('state_id' => '20','lga' => 'Dutsin Ma'),
            array('state_id' => '3','lga' => 'Eastern Obolo'),
            array('state_id' => '12','lga' => 'Ebonyi'),
            array('state_id' => '25','lga' => 'Edati'),
            array('state_id' => '28','lga' => 'Ede North'),
            array('state_id' => '28','lga' => 'Ede South'),
            array('state_id' => '23','lga' => 'Edu'),
            array('state_id' => '28','lga' => 'Ife Central'),
            array('state_id' => '28','lga' => 'Ife East'),
            array('state_id' => '28','lga' => 'Ife North'),
            array('state_id' => '28','lga' => 'Ife South'),
            array('state_id' => '13','lga' => 'Efon'),
            array('state_id' => '26','lga' => 'Egbado North'),
            array('state_id' => '26','lga' => 'Egbado South'),
            array('state_id' => '29','lga' => 'Egbeda'),
            array('state_id' => '28','lga' => 'Egbedore'),
            array('state_id' => '11','lga' => 'Egor'),
            array('state_id' => '16','lga' => 'Ehime Mbano'),
            array('state_id' => '28','lga' => 'Ejigbo'),
            array('state_id' => '6','lga' => 'Ekeremor'),
            array('state_id' => '3','lga' => 'Eket'),
            array('state_id' => '23','lga' => 'Ekiti'),
            array('state_id' => '13','lga' => 'Ekiti East'),
            array('state_id' => '13','lga' => 'Ekiti South-West'),
            array('state_id' => '13','lga' => 'Ekiti West'),
            array('state_id' => '4','lga' => 'Ekwusigo'),
            array('state_id' => '32','lga' => 'Eleme'),
            array('state_id' => '32','lga' => 'Emuoha'),
            array('state_id' => '13','lga' => 'Emure'),
            array('state_id' => '14','lga' => 'Enugu East'),
            array('state_id' => '14','lga' => 'Enugu North'),
            array('state_id' => '14','lga' => 'Enugu South'),
            array('state_id' => '24','lga' => 'Epe'),
            array('state_id' => '11','lga' => 'Esan Central'),
            array('state_id' => '11','lga' => 'Esan North-East'),
            array('state_id' => '11','lga' => 'Esan South-East'),
            array('state_id' => '11','lga' => 'Esan West'),
            array('state_id' => '27','lga' => 'Ese Odo'),
            array('state_id' => '3','lga' => 'Esit Eket'),
            array('state_id' => '3','lga' => 'Essien Udim'),
            array('state_id' => '32','lga' => 'Etche'),
            array('state_id' => '10','lga' => 'Ethiope East'),
            array('state_id' => '10','lga' => 'Ethiope West'),
            array('state_id' => '3','lga' => 'Etim Ekpo'),
            array('state_id' => '3','lga' => 'Etinan'),
            array('state_id' => '24','lga' => 'Eti Osa'),
            array('state_id' => '11','lga' => 'Etsako Central'),
            array('state_id' => '11','lga' => 'Etsako East'),
            array('state_id' => '11','lga' => 'Etsako West'),
            array('state_id' => '9','lga' => 'Etung'),
            array('state_id' => '26','lga' => 'Ewekoro'),
            array('state_id' => '14','lga' => 'Ezeagu'),
            array('state_id' => '16','lga' => 'Ezinihitte'),
            array('state_id' => '12','lga' => 'Ezza North'),
            array('state_id' => '12','lga' => 'Ezza South'),
            array('state_id' => '19','lga' => 'Fagge'),
            array('state_id' => '21','lga' => 'Fakai'),
            array('state_id' => '20','lga' => 'Faskari'),
            array('state_id' => '35','lga' => 'Fika'),
            array('state_id' => '2','lga' => 'Fufure'),
            array('state_id' => '15','lga' => 'Funakaye'),
            array('state_id' => '35','lga' => 'Fune'),
            array('state_id' => '20','lga' => 'Funtua'),
            array('state_id' => '19','lga' => 'Gabasawa'),
            array('state_id' => '33','lga' => 'Gada'),
            array('state_id' => '17','lga' => 'Gagarawa'),
            array('state_id' => '5','lga' => 'Gamawa'),
            array('state_id' => '5','lga' => 'Ganjuwa'),
            array('state_id' => '2','lga' => 'Ganye'),
            array('state_id' => '17','lga' => 'Garki'),
            array('state_id' => '19','lga' => 'Garko'),
            array('state_id' => '19','lga' => 'Garun Mallam'),
            array('state_id' => '34','lga' => 'Gashaka'),
            array('state_id' => '34','lga' => 'Gassol'),
            array('state_id' => '19','lga' => 'Gaya'),
            array('state_id' => '2','lga' => 'Gayuk'),
            array('state_id' => '19','lga' => 'Gezawa'),
            array('state_id' => '25','lga' => 'Gbako'),
            array('state_id' => '7','lga' => 'Gboko'),
            array('state_id' => '13','lga' => 'Gbonyin'),
            array('state_id' => '35','lga' => 'Geidam'),
            array('state_id' => '5','lga' => 'Giade'),
            array('state_id' => '18','lga' => 'Giwa'),
            array('state_id' => '32','lga' => 'Gokana'),
            array('state_id' => '15','lga' => 'Gombe'),
            array('state_id' => '2','lga' => 'Gombi'),
            array('state_id' => '33','lga' => 'Goronyo'),
            array('state_id' => '2','lga' => 'Grie'),
            array('state_id' => '8','lga' => 'Gubio'),
            array('state_id' => '33','lga' => 'Gudu'),
            array('state_id' => '35','lga' => 'Gujba'),
            array('state_id' => '35','lga' => 'Gulani'),
            array('state_id' => '7','lga' => 'Guma'),
            array('state_id' => '17','lga' => 'Gumel'),
            array('state_id' => '36','lga' => 'Gummi'),
            array('state_id' => '25','lga' => 'Gurara'),
            array('state_id' => '17','lga' => 'Guri'),
            array('state_id' => '36','lga' => 'Gusau'),
            array('state_id' => '8','lga' => 'Guzamala'),
            array('state_id' => '33','lga' => 'Gwadabawa'),
            array('state_id' => '37','lga' => 'Gwagwalada'),
            array('state_id' => '19','lga' => 'Gwale'),
            array('state_id' => '21','lga' => 'Gwandu'),
            array('state_id' => '17','lga' => 'Gwaram'),
            array('state_id' => '19','lga' => 'Gwarzo'),
            array('state_id' => '7','lga' => 'Gwer East'),
            array('state_id' => '7','lga' => 'Gwer West'),
            array('state_id' => '17','lga' => 'Gwiwa'),
            array('state_id' => '8','lga' => 'Gwoza'),
            array('state_id' => '17','lga' => 'Hadejia'),
            array('state_id' => '8','lga' => 'Hawul'),
            array('state_id' => '2','lga' => 'Hong'),
            array('state_id' => '29','lga' => 'Ibadan North'),
            array('state_id' => '29','lga' => 'Ibadan North-East'),
            array('state_id' => '29','lga' => 'Ibadan North-West'),
            array('state_id' => '29','lga' => 'Ibadan South-East'),
            array('state_id' => '29','lga' => 'Ibadan South-West'),
            array('state_id' => '22','lga' => 'Ibaji'),
            array('state_id' => '29','lga' => 'Ibarapa Central'),
            array('state_id' => '29','lga' => 'Ibarapa East'),
            array('state_id' => '29','lga' => 'Ibarapa North'),
            array('state_id' => '24','lga' => 'Ibeju-Lekki'),
            array('state_id' => '3','lga' => 'Ibeno'),
            array('state_id' => '3','lga' => 'Ibesikpo Asutan'),
            array('state_id' => '34','lga' => 'Ibi'),
            array('state_id' => '3','lga' => 'Ibiono-Ibom'),
            array('state_id' => '22','lga' => 'Idah'),
            array('state_id' => '27','lga' => 'Idanre'),
            array('state_id' => '16','lga' => 'Ideato North'),
            array('state_id' => '16','lga' => 'Ideato South'),
            array('state_id' => '4','lga' => 'Idemili North'),
            array('state_id' => '4','lga' => 'Idemili South'),
            array('state_id' => '29','lga' => 'Ido'),
            array('state_id' => '13','lga' => 'Ido Osi'),
            array('state_id' => '24','lga' => 'Ifako-Ijaiye'),
            array('state_id' => '28','lga' => 'Ifedayo'),
            array('state_id' => '27','lga' => 'Ifedore'),
            array('state_id' => '23','lga' => 'Ifelodun'),
            array('state_id' => '28','lga' => 'Ifelodun'),
            array('state_id' => '26','lga' => 'Ifo'),
            array('state_id' => '18','lga' => 'Igabi'),
            array('state_id' => '22','lga' => 'Igalamela Odolu'),
            array('state_id' => '14','lga' => 'Igbo Etiti'),
            array('state_id' => '14','lga' => 'Igbo Eze North'),
            array('state_id' => '14','lga' => 'Igbo Eze South'),
            array('state_id' => '11','lga' => 'Igueben'),
            array('state_id' => '4','lga' => 'Ihiala'),
            array('state_id' => '16','lga' => 'Ihitte/Uboma'),
            array('state_id' => '27','lga' => 'Ilaje'),
            array('state_id' => '26','lga' => 'Ijebu East'),
            array('state_id' => '26','lga' => 'Ijebu North'),
            array('state_id' => '26','lga' => 'Ijebu North East'),
            array('state_id' => '26','lga' => 'Ijebu Ode'),
            array('state_id' => '13','lga' => 'Ijero'),
            array('state_id' => '22','lga' => 'Ijumu'),
            array('state_id' => '3','lga' => 'Ika'),
            array('state_id' => '10','lga' => 'Ika North East'),
            array('state_id' => '18','lga' => 'Ikara'),
            array('state_id' => '10','lga' => 'Ika South'),
            array('state_id' => '16','lga' => 'Ikeduru'),
            array('state_id' => '24','lga' => 'Ikeja'),
            array('state_id' => '26','lga' => 'Ikenne'),
            array('state_id' => '13','lga' => 'Ikere'),
            array('state_id' => '13','lga' => 'Ikole'),
            array('state_id' => '9','lga' => 'Ikom'),
            array('state_id' => '3','lga' => 'Ikono'),
            array('state_id' => '24','lga' => 'Ikorodu'),
            array('state_id' => '3','lga' => 'Ikot Abasi'),
            array('state_id' => '3','lga' => 'Ikot Ekpene'),
            array('state_id' => '11','lga' => 'Ikpoba Okha'),
            array('state_id' => '32','lga' => 'Ikwerre'),
            array('state_id' => '12','lga' => 'Ikwo'),
            array('state_id' => '1','lga' => 'Ikwuano'),
            array('state_id' => '28','lga' => 'Ila'),
            array('state_id' => '13','lga' => 'Ilejemeje'),
            array('state_id' => '27','lga' => 'Ile Oluji/Okeigbo'),
            array('state_id' => '28','lga' => 'Ilesa East'),
            array('state_id' => '28','lga' => 'Ilesa West'),
            array('state_id' => '33','lga' => 'Illela'),
            array('state_id' => '23','lga' => 'Ilorin East'),
            array('state_id' => '23','lga' => 'Ilorin South'),
            array('state_id' => '23','lga' => 'Ilorin West'),
            array('state_id' => '26','lga' => 'Imeko Afon'),
            array('state_id' => '20','lga' => 'Ingawa'),
            array('state_id' => '3','lga' => 'Ini'),
            array('state_id' => '26','lga' => 'Ipokia'),
            array('state_id' => '27','lga' => 'Irele'),
            array('state_id' => '29','lga' => 'Irepo'),
            array('state_id' => '23','lga' => 'Irepodun'),
            array('state_id' => '28','lga' => 'Irepodun'),
            array('state_id' => '13','lga' => 'Irepodun/Ifelodun'),
            array('state_id' => '28','lga' => 'Irewole'),
            array('state_id' => '33','lga' => 'Isa'),
            array('state_id' => '13','lga' => 'Ise/Orun'),
            array('state_id' => '29','lga' => 'Iseyin'),
            array('state_id' => '12','lga' => 'Ishielu'),
            array('state_id' => '16','lga' => 'Isiala Mbano'),
            array('state_id' => '1','lga' => 'Isiala Ngwa North'),
            array('state_id' => '1','lga' => 'Isiala Ngwa South'),
            array('state_id' => '23','lga' => 'Isin'),
            array('state_id' => '14','lga' => 'Isi Uzo'),
            array('state_id' => '28','lga' => 'Isokan'),
            array('state_id' => '10','lga' => 'Isoko North'),
            array('state_id' => '10','lga' => 'Isoko South'),
            array('state_id' => '16','lga' => 'Isu'),
            array('state_id' => '1','lga' => 'Isuikwuato'),
            array('state_id' => '5','lga' => 'Itas/Gadau'),
            array('state_id' => '29','lga' => 'Itesiwaju'),
            array('state_id' => '3','lga' => 'Itu'),
            array('state_id' => '12','lga' => 'Ivo'),
            array('state_id' => '29','lga' => 'Iwajowa'),
            array('state_id' => '30','lga' => 'Iwo'),
            array('state_id' => '12','lga' => 'Izzi'),
            array('state_id' => '18','lga' => 'Jaba'),
            array('state_id' => '2','lga' => 'Jada'),
            array('state_id' => '17','lga' => 'Jahun'),
            array('state_id' => '35','lga' => 'Jakusko'),
            array('state_id' => '34','lga' => 'Jalingo'),
            array('state_id' => '5','lga' => 'Jama are'),
            array('state_id' => '21','lga' => 'Jega'),
            array('state_id' => '18','lga' => 'Jema a'),
            array('state_id' => '8','lga' => 'Jere'),
            array('state_id' => '20','lga' => 'Jibia'),
            array('state_id' => '31','lga' => 'Jos East'),
            array('state_id' => '31','lga' => 'Jos North'),
            array('state_id' => '31','lga' => 'Jos South'),
            array('state_id' => '22','lga' => 'Kabba/Bunu'),
            array('state_id' => '19','lga' => 'Kabo'),
            array('state_id' => '18','lga' => 'Kachia'),
            array('state_id' => '18','lga' => 'Kaduna North'),
            array('state_id' => '18','lga' => 'Kaduna South'),
            array('state_id' => '17','lga' => 'Kafin Hausa'),
            array('state_id' => '20','lga' => 'Kafur'),
            array('state_id' => '8','lga' => 'Kaga'),
            array('state_id' => '18','lga' => 'Kagarko'),
            array('state_id' => '23','lga' => 'Kaiama'),
            array('state_id' => '20','lga' => 'Kaita'),
            array('state_id' => '29','lga' => 'Kajola'),
            array('state_id' => '18','lga' => 'Kajuru'),
            array('state_id' => '8','lga' => 'Kala/Balge'),
            array('state_id' => '21','lga' => 'Kalgo'),
            array('state_id' => '15','lga' => 'Kaltungo'),
            array('state_id' => '31','lga' => 'Kanam'),
            array('state_id' => '20','lga' => 'Kankara'),
            array('state_id' => '31','lga' => 'Kanke'),
            array('state_id' => '20','lga' => 'Kankia'),
            array('state_id' => '19','lga' => 'Kano Municipal'),
            array('state_id' => '35','lga' => 'Karasuwa'),
            array('state_id' => '19','lga' => 'Karaye'),
            array('state_id' => '34','lga' => 'Karim Lamido'),
            array('state_id' => '30','lga' => 'Karu'),
            array('state_id' => '5','lga' => 'Katagum'),
            array('state_id' => '25','lga' => 'Katcha'),
            array('state_id' => '20','lga' => 'Katsina'),
            array('state_id' => '7','lga' => 'Katsina-Ala'),
            array('state_id' => '18','lga' => 'Kaura'),
            array('state_id' => '36','lga' => 'Kaura Namoda'),
            array('state_id' => '18','lga' => 'Kauru'),
            array('state_id' => '17','lga' => 'Kazaure'),
            array('state_id' => '30','lga' => 'Keana'),
            array('state_id' => '33','lga' => 'Kebbe'),
            array('state_id' => '30','lga' => 'Keffi'),
            array('state_id' => '32','lga' => 'Khana'),
            array('state_id' => '19','lga' => 'Kibiya'),
            array('state_id' => '5','lga' => 'Kirfi'),
            array('state_id' => '17','lga' => 'Kiri Kasama'),
            array('state_id' => '19','lga' => 'Kiru'),
            array('state_id' => '17','lga' => 'Kiyawa'),
            array('state_id' => '22','lga' => 'Kogi'),
            array('state_id' => '21','lga' => 'Koko/Besse'),
            array('state_id' => '30','lga' => 'Kokona'),
            array('state_id' => '6','lga' => 'Kolokuma/Opokuma'),
            array('state_id' => '8','lga' => 'Konduga'),
            array('state_id' => '7','lga' => 'Konshisha'),
            array('state_id' => '25','lga' => 'Kontagora'),
            array('state_id' => '24','lga' => 'Kosofe'),
            array('state_id' => '17','lga' => 'Kaugama'),
            array('state_id' => '18','lga' => 'Kubau'),
            array('state_id' => '18','lga' => 'Kudan'),
            array('state_id' => '37','lga' => 'Kuje'),
            array('state_id' => '8','lga' => 'Kukawa'),
            array('state_id' => '19','lga' => 'Kumbotso'),
            array('state_id' => '34','lga' => 'Kumi'),
            array('state_id' => '19','lga' => 'Kunchi'),
            array('state_id' => '19','lga' => 'Kura'),
            array('state_id' => '20','lga' => 'Kurfi'),
            array('state_id' => '20','lga' => 'Kusada'),
            array('state_id' => '37','lga' => 'Kwali'),
            array('state_id' => '7','lga' => 'Kwande'),
            array('state_id' => '15','lga' => 'Kwami'),
            array('state_id' => '33','lga' => 'Kware'),
            array('state_id' => '8','lga' => 'Kwaya Kusar'),
            array('state_id' => '30','lga' => 'Lafia'),
            array('state_id' => '29','lga' => 'Lagelu'),
            array('state_id' => '24','lga' => 'Lagos Island'),
            array('state_id' => '24','lga' => 'Lagos Mainland'),
            array('state_id' => '31','lga' => 'Langtang South'),
            array('state_id' => '31','lga' => 'Langtang North'),
            array('state_id' => '25','lga' => 'Lapai'),
            array('state_id' => '2','lga' => 'Lamurde'),
            array('state_id' => '34','lga' => 'Lau'),
            array('state_id' => '25','lga' => 'Lavun'),
            array('state_id' => '18','lga' => 'Lere'),
            array('state_id' => '7','lga' => 'Logo'),
            array('state_id' => '22','lga' => 'Lokoja'),
            array('state_id' => '35','lga' => 'Machina'),
            array('state_id' => '2','lga' => 'Madagali'),
            array('state_id' => '19','lga' => 'Madobi'),
            array('state_id' => '8','lga' => 'Mafa'),
            array('state_id' => '25','lga' => 'Magama'),
            array('state_id' => '8','lga' => 'Magumeri'),
            array('state_id' => '20','lga' => 'Mai Adua'),
            array('state_id' => '8','lga' => 'Maiduguri'),
            array('state_id' => '17','lga' => 'Maigatari'),
            array('state_id' => '2','lga' => 'Maiha'),
            array('state_id' => '21','lga' => 'Maiyama'),
            array('state_id' => '18','lga' => 'Makarfi'),
            array('state_id' => '19','lga' => 'Makoda'),
            array('state_id' => '17','lga' => 'Malam Madori'),
            array('state_id' => '20','lga' => 'Malumfashi'),
            array('state_id' => '31','lga' => 'Mangu'),
            array('state_id' => '20','lga' => 'Mani'),
            array('state_id' => '36','lga' => 'Maradun'),
            array('state_id' => '25','lga' => 'Mariga'),
            array('state_id' => '7','lga' => 'Makurdi'),
            array('state_id' => '8','lga' => 'Marte'),
            array('state_id' => '36','lga' => 'Maru'),
            array('state_id' => '25','lga' => 'Mashegu'),
            array('state_id' => '20','lga' => 'Mashi'),
            array('state_id' => '20','lga' => 'Matazu'),
            array('state_id' => '2','lga' => 'Mayo Belwa'),
            array('state_id' => '16','lga' => 'Mbaitoli'),
            array('state_id' => '3','lga' => 'Mbo'),
            array('state_id' => '2','lga' => 'Michika'),
            array('state_id' => '17','lga' => 'Miga'),
            array('state_id' => '31','lga' => 'Mikang'),
            array('state_id' => '19','lga' => 'Minjibir'),
            array('state_id' => '5','lga' => 'Misau'),
            array('state_id' => '13','lga' => 'Moba'),
            array('state_id' => '8','lga' => 'Mobbar'),
            array('state_id' => '2','lga' => 'Mubi North'),
            array('state_id' => '2','lga' => 'Mubi South'),
            array('state_id' => '25','lga' => 'Mokwa'),
            array('state_id' => '8','lga' => 'Monguno'),
            array('state_id' => '22','lga' => 'Mopa Muro'),
            array('state_id' => '23','lga' => 'Moro'),
            array('state_id' => '25','lga' => 'Moya'),
            array('state_id' => '3','lga' => 'Mkpat-Enin'),
            array('state_id' => '37','lga' => 'Municipal Area Council'),
            array('state_id' => '20','lga' => 'Musawa'),
            array('state_id' => '24','lga' => 'Mushin'),
            array('state_id' => '15','lga' => 'Nafada'),
            array('state_id' => '35','lga' => 'Nangere'),
            array('state_id' => '19','lga' => 'Nasarawa'),
            array('state_id' => '30','lga' => 'Nasarawa'),
            array('state_id' => '30','lga' => 'Nasarawa Egon'),
            array('state_id' => '10','lga' => 'Ndokwa East'),
            array('state_id' => '10','lga' => 'Ndokwa West'),
            array('state_id' => '6','lga' => 'Nembe'),
            array('state_id' => '8','lga' => 'Ngala'),
            array('state_id' => '8','lga' => 'Nganzai'),
            array('state_id' => '21','lga' => 'Ngaski'),
            array('state_id' => '16','lga' => 'Ngor Okpala'),
            array('state_id' => '35','lga' => 'Nguru'),
            array('state_id' => '5','lga' => 'Ningi'),
            array('state_id' => '16','lga' => 'Njaba'),
            array('state_id' => '4','lga' => 'Njikoka'),
            array('state_id' => '14','lga' => 'Nkanu East'),
            array('state_id' => '14','lga' => 'Nkanu West'),
            array('state_id' => '16','lga' => 'Nkwerre'),
            array('state_id' => '4','lga' => 'Nnewi North'),
            array('state_id' => '4','lga' => 'Nnewi South'),
            array('state_id' => '3','lga' => 'Nsit-Atai'),
            array('state_id' => '3','lga' => 'Nsit-Ibom'),
            array('state_id' => '3','lga' => 'Nsit-Ubium'),
            array('state_id' => '14','lga' => 'Nsukka'),
            array('state_id' => '2','lga' => 'Numan'),
            array('state_id' => '16','lga' => 'Nwangele'),
            array('state_id' => '26','lga' => 'Obafemi Owode'),
            array('state_id' => '9','lga' => 'Obanliku'),
            array('state_id' => '7','lga' => 'Obi'),
            array('state_id' => '30','lga' => 'Obi'),
            array('state_id' => '1','lga' => 'Obi Ngwa'),
            array('state_id' => '32','lga' => 'Obio/Akpor'),
            array('state_id' => '28','lga' => 'Obokun'),
            array('state_id' => '3','lga' => 'Obot Akara'),
            array('state_id' => '16','lga' => 'Obowo'),
            array('state_id' => '9','lga' => 'Obubra'),
            array('state_id' => '9','lga' => 'Obudu'),
            array('state_id' => '26','lga' => 'Odeda'),
            array('state_id' => '27','lga' => 'Odigbo'),
            array('state_id' => '26','lga' => 'Odogbolu'),
            array('state_id' => '28','lga' => 'Odo Otin'),
            array('state_id' => '9','lga' => 'Odukpani'),
            array('state_id' => '23','lga' => 'Offa'),
            array('state_id' => '22','lga' => 'Ofu'),
            array('state_id' => '32','lga' => 'Ogba/Egbema/Ndoni'),
            array('state_id' => '7','lga' => 'Ogbadibo'),
            array('state_id' => '4','lga' => 'Ogbaru'),
            array('state_id' => '6','lga' => 'Ogbia'),
            array('state_id' => '29','lga' => 'Ogbomosho North'),
            array('state_id' => '29','lga' => 'Ogbomosho South'),
            array('state_id' => '32','lga' => 'Ogu/Bolo'),
            array('state_id' => '9','lga' => 'Ogoja'),
            array('state_id' => '29','lga' => 'Ogo Oluwa'),
            array('state_id' => '22','lga' => 'Ogori/Magongo'),
            array('state_id' => '26','lga' => 'Ogun Waterside'),
            array('state_id' => '16','lga' => 'Oguta'),
            array('state_id' => '1','lga' => 'Ohafia'),
            array('state_id' => '16','lga' => 'Ohaji/Egbema'),
            array('state_id' => '12','lga' => 'Ohaozara'),
            array('state_id' => '12','lga' => 'Ohaukwu'),
            array('state_id' => '7','lga' => 'Ohimini'),
            array('state_id' => '11','lga' => 'Orhionmwon'),
            array('state_id' => '14','lga' => 'Oji River'),
            array('state_id' => '24','lga' => 'Ojo'),
            array('state_id' => '7','lga' => 'Oju'),
            array('state_id' => '22','lga' => 'Okehi'),
            array('state_id' => '22','lga' => 'Okene'),
            array('state_id' => '23','lga' => 'Oke Ero'),
            array('state_id' => '16','lga' => 'Okigwe'),
            array('state_id' => '27','lga' => 'Okitipupa'),
            array('state_id' => '3','lga' => 'Okobo'),
            array('state_id' => '10','lga' => 'Okpe'),
            array('state_id' => '32','lga' => 'Okrika'),
            array('state_id' => '22','lga' => 'Olamaboro'),
            array('state_id' => '28','lga' => 'Ola Oluwa'),
            array('state_id' => '28','lga' => 'Olorunda'),
            array('state_id' => '29','lga' => 'Olorunsogo'),
            array('state_id' => '29','lga' => 'Oluyole'),
            array('state_id' => '22','lga' => 'Omala'),
            array('state_id' => '32','lga' => 'Omuma'),
            array('state_id' => '29','lga' => 'Ona Ara'),
            array('state_id' => '27','lga' => 'Ondo East'),
            array('state_id' => '27','lga' => 'Ondo West'),
            array('state_id' => '12','lga' => 'Onicha'),
            array('state_id' => '4','lga' => 'Onitsha North'),
            array('state_id' => '4','lga' => 'Onitsha South'),
            array('state_id' => '3','lga' => 'Onna'),
            array('state_id' => '7','lga' => 'Okpokwu'),
            array('state_id' => '32','lga' => 'Opobo/Nkoro'),
            array('state_id' => '11','lga' => 'Oredo'),
            array('state_id' => '29','lga' => 'Orelope'),
            array('state_id' => '28','lga' => 'Oriade'),
            array('state_id' => '29','lga' => 'Ori Ire'),
            array('state_id' => '16','lga' => 'Orlu'),
            array('state_id' => '28','lga' => 'Orolu'),
            array('state_id' => '3','lga' => 'Oron'),
            array('state_id' => '16','lga' => 'Orsu'),
            array('state_id' => '16','lga' => 'Oru East'),
            array('state_id' => '3','lga' => 'Oruk Anam'),
            array('state_id' => '4','lga' => 'Orumba North'),
            array('state_id' => '4','lga' => 'Orumba South'),
            array('state_id' => '16','lga' => 'Oru West'),
            array('state_id' => '27','lga' => 'Ose'),
            array('state_id' => '10','lga' => 'Oshimili North'),
            array('state_id' => '10','lga' => 'Oshimili South'),
            array('state_id' => '24','lga' => 'Oshodi-Isolo'),
            array('state_id' => '1','lga' => 'Osisioma'),
            array('state_id' => '28','lga' => 'Osogbo'),
            array('state_id' => '7','lga' => 'Oturkpo'),
            array('state_id' => '11','lga' => 'Ovia North-East'),
            array('state_id' => '11','lga' => 'Ovia South-West'),
            array('state_id' => '11','lga' => 'Owan East'),
            array('state_id' => '11','lga' => 'Owan West'),
            array('state_id' => '16','lga' => 'Owerri Municipal'),
            array('state_id' => '16','lga' => 'Owerri North'),
            array('state_id' => '16','lga' => 'Owerri West'),
            array('state_id' => '27','lga' => 'Owo'),
            array('state_id' => '13','lga' => 'Oye'),
            array('state_id' => '4','lga' => 'Oyi'),
            array('state_id' => '32','lga' => 'Oyigbo'),
            array('state_id' => '29','lga' => 'Oyo'),
            array('state_id' => '29','lga' => 'Oyo East'),
            array('state_id' => '23','lga' => 'Oyun'),
            array('state_id' => '25','lga' => 'Paikoro'),
            array('state_id' => '31','lga' => 'Pankshin'),
            array('state_id' => '10','lga' => 'Patani'),
            array('state_id' => '23','lga' => 'Pategi'),
            array('state_id' => '32','lga' => 'Port Harcourt'),
            array('state_id' => '35','lga' => 'Potiskum'),
            array('state_id' => '31','lga' => 'Qua an Pan'),
            array('state_id' => '33','lga' => 'Rabah'),
            array('state_id' => '25','lga' => 'Rafi'),
            array('state_id' => '19','lga' => 'Rano'),
            array('state_id' => '26','lga' => 'Remo North'),
            array('state_id' => '25','lga' => 'Rijau'),
            array('state_id' => '20','lga' => 'Rimi'),
            array('state_id' => '19','lga' => 'Rimin Gado'),
            array('state_id' => '17','lga' => 'Ringim'),
            array('state_id' => '31','lga' => 'Riyom'),
            array('state_id' => '19','lga' => 'Rogo'),
            array('state_id' => '17','lga' => 'Roni'),
            array('state_id' => '33','lga' => 'Sabon Birni'),
            array('state_id' => '18','lga' => 'Sabon Gari'),
            array('state_id' => '20','lga' => 'Sabuwa'),
            array('state_id' => '20','lga' => 'Safana'),
            array('state_id' => '6','lga' => 'Sagbama'),
            array('state_id' => '21','lga' => 'Sakaba'),
            array('state_id' => '29','lga' => 'Saki East'),
            array('state_id' => '29','lga' => 'Saki West'),
            array('state_id' => '20','lga' => 'Sandamu'),
            array('state_id' => '18','lga' => 'Sanga'),
            array('state_id' => '10','lga' => 'Sapele'),
            array('state_id' => '34','lga' => 'Sardauna'),
            array('state_id' => '26','lga' => 'Shagamu'),
            array('state_id' => '33','lga' => 'Shagari'),
            array('state_id' => '21','lga' => 'Shanga'),
            array('state_id' => '8','lga' => 'Shani'),
            array('state_id' => '19','lga' => 'Shanono'),
            array('state_id' => '2','lga' => 'Shelleng'),
            array('state_id' => '31','lga' => 'Shendam'),
            array('state_id' => '36','lga' => 'Shinkafi'),
            array('state_id' => '5','lga' => 'Shira'),
            array('state_id' => '25','lga' => 'Shiroro'),
            array('state_id' => '15','lga' => 'Shongom'),
            array('state_id' => '24','lga' => 'Shomolu'),
            array('state_id' => '33','lga' => 'Silame'),
            array('state_id' => '18','lga' => 'Soba'),
            array('state_id' => '33','lga' => 'Sokoto North'),
            array('state_id' => '33','lga' => 'Sokoto South'),
            array('state_id' => '2','lga' => 'Song'),
            array('state_id' => '6','lga' => 'Southern Ijaw'),
            array('state_id' => '25','lga' => 'Suleja'),
            array('state_id' => '17','lga' => 'Sule Tankarkar'),
            array('state_id' => '19','lga' => 'Sumaila'),
            array('state_id' => '21','lga' => 'Suru'),
            array('state_id' => '29','lga' => 'Surulere'),
            array('state_id' => '24','lga' => 'Surulere'),
            array('state_id' => '25','lga' => 'Tafa'),
            array('state_id' => '5','lga' => 'Tafawa Balewa'),
            array('state_id' => '32','lga' => 'Tai'),
            array('state_id' => '19','lga' => 'Takai'),
            array('state_id' => '34','lga' => 'Takum'),
            array('state_id' => '36','lga' => 'Talata Mafara'),
            array('state_id' => '33','lga' => 'Tambuwal'),
            array('state_id' => '33','lga' => 'Tangaza'),
            array('state_id' => '19','lga' => 'Tarauni'),
            array('state_id' => '7','lga' => 'Tarka'),
            array('state_id' => '35','lga' => 'Tarmuwa'),
            array('state_id' => '17','lga' => 'Taura'),
            array('state_id' => '2','lga' => 'Toungo'),
            array('state_id' => '19','lga' => 'Tofa'),
            array('state_id' => '5','lga' => 'Toro'),
            array('state_id' => '30','lga' => 'Toto'),
            array('state_id' => '36','lga' => 'Chafe'),
            array('state_id' => '19','lga' => 'Tsanyawa'),
            array('state_id' => '19','lga' => 'Tudun Wada'),
            array('state_id' => '33','lga' => 'Tureta'),
            array('state_id' => '14','lga' => 'Udenu'),
            array('state_id' => '14','lga' => 'Udi'),
            array('state_id' => '10','lga' => 'Udu'),
            array('state_id' => '3','lga' => 'Udung-Uko'),
            array('state_id' => '10','lga' => 'Ughelli North'),
            array('state_id' => '10','lga' => 'Ughelli South'),
            array('state_id' => '1','lga' => 'Ugwunagbo'),
            array('state_id' => '11','lga' => 'Uhunmwonde'),
            array('state_id' => '3','lga' => 'Ukanafun'),
            array('state_id' => '7','lga' => 'Ukum'),
            array('state_id' => '1','lga' => 'Ukwa East'),
            array('state_id' => '1','lga' => 'Ukwa West'),
            array('state_id' => '10','lga' => 'Ukwuani'),
            array('state_id' => '1','lga' => 'Umuahia North'),
            array('state_id' => '1','lga' => 'Umuahia South'),
            array('state_id' => '1','lga' => 'Umu Nneochi'),
            array('state_id' => '19','lga' => 'Ungogo'),
            array('state_id' => '16','lga' => 'Unuimo'),
            array('state_id' => '3','lga' => 'Uruan'),
            array('state_id' => '3','lga' => 'Urue-Offong/Oruko'),
            array('state_id' => '7','lga' => 'Ushongo'),
            array('state_id' => '34','lga' => 'Ussa'),
            array('state_id' => '10','lga' => 'Uvwie'),
            array('state_id' => '3','lga' => 'Uyo'),
            array('state_id' => '14','lga' => 'Uzo Uwani'),
            array('state_id' => '7','lga' => 'Vandeikya'),
            array('state_id' => '33','lga' => 'Wamako'),
            array('state_id' => '30','lga' => 'Wamba'),
            array('state_id' => '19','lga' => 'Warawa'),
            array('state_id' => '5','lga' => 'Warji'),
            array('state_id' => '10','lga' => 'Warri North'),
            array('state_id' => '10','lga' => 'Warri South'),
            array('state_id' => '10','lga' => 'Warri South West'),
            array('state_id' => '21','lga' => 'Wasagu/Danko'),
            array('state_id' => '31','lga' => 'Wase'),
            array('state_id' => '19','lga' => 'Wudil'),
            array('state_id' => '34','lga' => 'Wukari'),
            array('state_id' => '33','lga' => 'Wurno'),
            array('state_id' => '25','lga' => 'Wushishi'),
            array('state_id' => '33','lga' => 'Yabo'),
            array('state_id' => '22','lga' => 'Yagba East'),
            array('state_id' => '22','lga' => 'Yagba West'),
            array('state_id' => '9','lga' => 'Yakuur'),
            array('state_id' => '9','lga' => 'Yala'),
            array('state_id' => '15','lga' => 'Yamaltu/Deba'),
            array('state_id' => '17','lga' => 'Yankwashi'),
            array('state_id' => '21','lga' => 'Yauri'),
            array('state_id' => '6','lga' => 'Yenagoa'),
            array('state_id' => '2','lga' => 'Yola North'),
            array('state_id' => '2','lga' => 'Yola South'),
            array('state_id' => '34','lga' => 'Yorro'),
            array('state_id' => '35','lga' => 'Yunusari'),
            array('state_id' => '35','lga' => 'Yusufari'),
            array('state_id' => '5','lga' => 'Zaki'),
            array('state_id' => '20','lga' => 'Zango'),
            array('state_id' => '18','lga' => 'Zangon Kataf'),
            array('state_id' => '18','lga' => 'Zaria'),
            array('state_id' => '34','lga' => 'Zing'),
            array('state_id' => '36','lga' => 'Zurmi'),
            array('state_id' => '21','lga' => 'Zuru')
          );

          foreach($lgas as $lga){
            LGA::create($lga);
          }
          
    }
}
